export const ENCUESTA_100K_INTRO = {
  title: "Mi Punto de Partida",
  subtitle: "Manual de Negocio 100K",
  description:
    "Este es el único tab del manual que se llena a mano: con lo que respondas acá se genera todo lo demás. Tomate tu tiempo y contestá con historias y datos concretos, no con generalidades.",
};

export const FORM_SECTIONS_100K = [
  {
    id: "datos-basicos",
    title: "Datos Básicos",
    description: "Para ubicar tu contexto",
    fields: [
      { name: "nombre", label: "Tu nombre", type: "text", required: true },
      { name: "email", label: "Tu email", type: "text", required: true },
      { name: "negocioNicho", label: "Negocio / Nicho", type: "text", required: true, placeholder: "Tu nicho" },
      { name: "objetivo12Meses", label: "Objetivo en 12 meses", type: "textarea", required: true, placeholder: "Escribí tu meta" },
    ],
  },
  {
    id: "la-puerta",
    title: "1.1 La Puerta",
    description: "¿Ya tenés algo concreto que vender? (algo que si alguien te escribe hoy, le podés cobrar)",
    fields: [
      {
        name: "puerta",
        label: "¿Ya tenés algo concreto que vender?",
        type: "select",
        required: true,
        options: [
          { value: "si", label: "Sí → soy Puerta A" },
          { value: "no", label: "No → soy Puerta B" },
        ],
      },
    ],
  },
  {
    id: "mi-info",
    title: "1.2 Mi Info Actual / Mi Punto de Arranque",
    description: "La única diferencia entre las dos puertas es este punto. De acá en más se llena todo igual.",
    fields: [
      {
        name: "queVendesActualmente",
        label: "¿Qué vendés actualmente? (producto o servicio, con lo que incluye)",
        type: "textarea",
        required: true,
        showIf: (data: Record<string, any>) => data.puerta === "si",
      },
      {
        name: "aQuienLeVendes",
        label: "¿A quién le vendés? (tu cliente real de hoy, no el ideal)",
        type: "textarea",
        required: true,
        showIf: (data: Record<string, any>) => data.puerta === "si",
      },
      {
        name: "aQuePrecioVendes",
        label: "¿A qué precio vendés? (precio o rango, con la moneda)",
        type: "text",
        required: true,
        showIf: (data: Record<string, any>) => data.puerta === "si",
      },
      {
        name: "cuantoFacturasAlMes",
        label: "¿Cuánto facturás al mes? (cantidad aproximada)",
        type: "text",
        required: true,
        showIf: (data: Record<string, any>) => data.puerta === "si",
      },
      {
        name: "deDondeLleganClientes",
        label: "¿De dónde te llegan hoy los clientes? (recomendación, redes, DM, anuncios...)",
        type: "textarea",
        required: true,
        showIf: (data: Record<string, any>) => data.puerta === "si",
      },
      {
        name: "objecionMasEscuchas",
        label: "¿Qué objeción escuchás más antes de que te compren? (con sus palabras)",
        type: "textarea",
        required: true,
        showIf: (data: Record<string, any>) => data.puerta === "si",
      },
      {
        name: "queNoEstaFuncionando",
        label: "¿Qué no está funcionando? (sé honesto)",
        type: "textarea",
        required: true,
        showIf: (data: Record<string, any>) => data.puerta === "si",
      },
      {
        name: "queSabesHacer",
        label: "¿Qué sabés hacer que a otra persona le costaría?",
        type: "textarea",
        required: true,
        showIf: (data: Record<string, any>) => data.puerta === "no",
      },
      {
        name: "quePreguntanConocidos",
        label: "¿Qué te preguntan tus conocidos cuando necesitan ayuda?",
        type: "textarea",
        required: true,
        showIf: (data: Record<string, any>) => data.puerta === "no",
      },
      {
        name: "aQuienHasAyudado",
        label: "¿A quién has ayudado con esto, aunque haya sido gratis?",
        type: "textarea",
        required: true,
        showIf: (data: Record<string, any>) => data.puerta === "no",
      },
      {
        name: "queIntentasteAntes",
        label: "¿Qué intentaste antes que no funcionó, y por qué creés que fue?",
        type: "textarea",
        required: true,
        showIf: (data: Record<string, any>) => data.puerta === "no",
      },
      {
        name: "cuantoTiempoDedicas",
        label: "¿Cuánto tiempo real por semana podés dedicarle?",
        type: "text",
        required: true,
        showIf: (data: Record<string, any>) => data.puerta === "no",
      },
    ],
  },
  {
    id: "punto-cero",
    title: "1.3 Mi Punto Cero",
    fields: [
      {
        name: "categoriaVida",
        label: "Categoría de vida (elegí 1, máximo 2)",
        type: "text",
        required: true,
        placeholder: "Amor · Familia · Cuerpo y mente · Identidad · Trabajo · Dinero · Ocio · Espiritualidad y propósito",
      },
      {
        name: "monedaEntrada",
        label: "Moneda de entrada",
        type: "select",
        required: true,
        options: [
          { value: "experiencia", label: "Experiencia" },
          { value: "investigacion", label: "Investigación" },
          { value: "produccion", label: "Producción" },
          { value: "divulgacion", label: "Divulgación" },
          { value: "perspectiva-propia", label: "Perspectiva propia" },
        ],
      },
      {
        name: "rubro",
        label: "Rubro (el campo que te da vocabulario propio)",
        type: "text",
        required: true,
      },
      {
        name: "nicho",
        label: "Nicho (a quién y en qué momento exacto de su vida)",
        type: "textarea",
        required: true,
      },
    ],
  },
  {
    id: "paradigma",
    title: "1.4 Mi Paradigma Único",
    description: "Pasá el Taladro antes de escribir: preguntate «¿y cuál es la clave de eso?» tres veces seguidas.",
    fields: [
      {
        name: "consensoDeMiRubro",
        label: "Lo que TODOS dicen en tu rubro sobre este problema (el consenso que vas a matar)",
        type: "textarea",
        required: true,
      },
      {
        name: "loQueYoSostengo",
        label: "Lo que VOS sostenés («el problema no es X, es Y»)",
        type: "textarea",
        required: true,
      },
      {
        name: "comoLoLlamo",
        label: "Cómo lo llamás (2 o 3 palabras)",
        type: "text",
        required: true,
      },
      {
        name: "queSignificaEnConcreto",
        label: "Qué significa en concreto (3 características; cada una es además un video)",
        type: "textarea",
        required: true,
      },
    ],
  },
  {
    id: "mi-historia",
    title: "1.5 Mi Historia ⭐",
    description:
      "Esto se convierte en tu Post de Autoridad. Nadie te sigue por tu currículum: te sigue porque se ve a sí misma en tu «antes». Escribí ESCENAS, no cualidades.",
    fields: [
      {
        name: "cuandoEmpezo",
        label: "¿Cuándo empezó? (una fecha o un tiempo concreto: «hace 3 años», «en marzo de 2023»)",
        type: "text",
        required: true,
      },
      {
        name: "elFondo",
        label: "El fondo: ¿cómo era tu situación antes del cambio?",
        type: "textarea",
        required: true,
      },
      {
        name: "laEmocion",
        label: "La emoción que unía esos datos",
        type: "textarea",
        required: true,
      },
      {
        name: "elGiro",
        label: "El giro: ¿qué cambió?",
        type: "textarea",
        required: true,
      },
      {
        name: "laPrueba",
        label: "La prueba: el resultado concreto de hoy",
        type: "textarea",
        required: true,
      },
      {
        name: "laObjecionSinArgumento",
        label: "¿Qué objeción deja sin argumento el resultado que lograste?",
        type: "textarea",
        required: false,
      },
      {
        name: "loQueTodaviaCuesta",
        label: "Lo que todavía te cuesta (sé honesto)",
        type: "textarea",
        required: false,
      },
      {
        name: "laFraseParaOtro",
        label: "La frase que le dirías a quien está hoy donde vos estabas",
        type: "textarea",
        required: true,
      },
    ],
  },
  {
    id: "testimonios",
    title: "1.6 Mis Testimonios y Pruebas ⭐",
    description: "Si no tenés producto o servicio todavía, contá lo que tengas de prueba igual (aunque sea informal) o dejalo en blanco.",
    fields: [
      {
        name: "testimoniosYPruebas",
        label: "Tus pruebas: antes/después, a quién ayudaste (aunque haya sido gratis), mensajes de agradecimiento",
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "presencia-digital",
    title: "1.7 Presencia Digital",
    fields: [
      { name: "instagram", label: "Instagram (usuario y seguidores)", type: "text", required: false },
      { name: "tiktok", label: "TikTok (usuario y seguidores)", type: "text", required: false },
      { name: "youtube", label: "YouTube (usuario y seguidores)", type: "text", required: false },
      { name: "bioActual", label: "Qué dice tu bio hoy, literal", type: "textarea", required: false },
      {
        name: "fotoPerfilActual",
        label: "Sobre tu foto de perfil de hoy: ¿cumple con cara visible, mirada a cámara, sonriendo, buena luz y fondo limpio? ¿Qué le falta?",
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "objetivo-personal",
    title: "1.8 Objetivo Personal",
    fields: [
      {
        name: "queQuieresLograr",
        label: "¿Qué querés lograr al terminar el programa?",
        type: "textarea",
        required: true,
      },
      {
        name: "comoSabrasQueLoLograste",
        label: "¿Cómo sabrás que lo lograste?",
        type: "textarea",
        required: true,
      },
      {
        name: "observaciones",
        label: "¿Algo más que quieras agregar?",
        type: "textarea",
        required: false,
      },
    ],
  },

  // ===================================================
  // TABS 6-19 (preguntas y campos adicionales del manual)
  // ===================================================
  {
    id: "t6-pilares",
    title: "6.1 Mis 3 Pilares de Contenido",
    fields: [
      { name: "t6_pilar1Nombre", label: "Pilar #1 (PROBLEMA) — Nombre del pilar", type: "text", required: false },
      { name: "t6_pilar1Lineas", label: "Pilar #1 (PROBLEMA) — Líneas narrativas de este pilar", type: "textarea", required: false },
      { name: "t6_pilar1Palabras", label: "Pilar #1 (PROBLEMA) — Palabras clave para investigación", type: "text", required: false },
      { name: "t6_pilar2Nombre", label: "Pilar #2 (SOLUCIÓN) — Nombre del pilar", type: "text", required: false },
      { name: "t6_pilar2Lineas", label: "Pilar #2 (SOLUCIÓN) — Líneas narrativas de este pilar", type: "textarea", required: false },
      { name: "t6_pilar2Palabras", label: "Pilar #2 (SOLUCIÓN) — Palabras clave para investigación", type: "text", required: false },
      { name: "t6_pilar3Nombre", label: "Pilar #3 (RESULTADO) — Nombre del pilar", type: "text", required: false },
      { name: "t6_pilar3Lineas", label: "Pilar #3 (RESULTADO) — Líneas narrativas de este pilar", type: "textarea", required: false },
      { name: "t6_pilar3Palabras", label: "Pilar #3 (RESULTADO) — Palabras clave para investigación", type: "text", required: false },
    ],
  },
  {
    id: "t6-investigacion",
    title: "6.2 Investigación de Contenido BASE",
    fields: [
      { name: "t6_keyword1", label: "Palabra clave #1 (volumen/relevancia y pilar al que pertenece)", type: "text", required: false },
      { name: "t6_keyword2", label: "Palabra clave #2 (volumen/relevancia y pilar al que pertenece)", type: "text", required: false },
      { name: "t6_keyword3", label: "Palabra clave #3 (volumen/relevancia y pilar al que pertenece)", type: "text", required: false },
      { name: "t6_competidoresAnalizados", label: "Competidores del rubro que analicé", type: "textarea", required: false },
      { name: "t6_ideasRepiten", label: "Ideas que más se repiten en mi nicho", type: "textarea", required: false },
      { name: "t6_formatosRepiten", label: "Formatos que más se repiten", type: "textarea", required: false },
    ],
  },
  {
    id: "t6-consciencia",
    title: "6.3 Niveles de Consciencia Mapeados",
    description: "Qué formatos o ideas creás para cada nivel",
    fields: [
      { name: "t6_nivel1Formatos", label: "Nivel 1 — Consciencia Baja (público frío, recién descubre su problema): qué formatos o ideas creás", type: "textarea", required: false },
      { name: "t6_nivel2Formatos", label: "Nivel 2 — Consciencia Media (ya conoce su problema, compara opciones): qué formatos o ideas creás", type: "textarea", required: false },
      { name: "t6_nivel3Formatos", label: "Nivel 3 — Consciencia Avanzada (ya probó soluciones, no le funcionaron): qué formatos o ideas creás", type: "textarea", required: false },
      { name: "t6_nivel4Formatos", label: "Nivel 4 — Consciencia Total (listo para comprar): qué formatos o ideas creás", type: "textarea", required: false },
    ],
  },
  {
    id: "t6-formatos-priorizados",
    title: "6.4 Formatos Priorizados por Nivel de Consciencia",
    fields: [
      { name: "t6_formatoPriorizado1", label: "Formato priorizado #1 (y a qué nivel de consciencia corresponde)", type: "text", required: false },
      { name: "t6_formatoPriorizado2", label: "Formato priorizado #2 (y a qué nivel de consciencia corresponde)", type: "text", required: false },
      { name: "t6_formatoPriorizado3", label: "Formato priorizado #3 (y a qué nivel de consciencia corresponde)", type: "text", required: false },
    ],
  },
  {
    id: "t6-ideas-crudo",
    title: "6.5 Lista de Ideas en Crudo",
    description: "Registrá acá todas las ideas que encuentres antes de filtrarlas",
    fields: [
      { name: "t6_idea1", label: "Idea #1", type: "text", required: false },
      { name: "t6_idea2", label: "Idea #2", type: "text", required: false },
      { name: "t6_idea3", label: "Idea #3", type: "text", required: false },
      { name: "t6_idea4", label: "Idea #4", type: "text", required: false },
      { name: "t6_idea5", label: "Idea #5", type: "text", required: false },
      { name: "t6_idea6", label: "Idea #6", type: "text", required: false },
    ],
  },
  {
    id: "t6-clasifica",
    title: "6.6 Clasificá lo Encontrado (Viralidad vs. Valor vs. Venta)",
    description: "Para cada idea: Idea → Propósito (viral/valor/venta) → Formato sugerido",
    fields: [
      { name: "t6_clasifica1", label: "Clasificación #1 (Idea → Propósito → Formato)", type: "text", required: false },
      { name: "t6_clasifica2", label: "Clasificación #2 (Idea → Propósito → Formato)", type: "text", required: false },
      { name: "t6_clasifica3", label: "Clasificación #3 (Idea → Propósito → Formato)", type: "text", required: false },
      { name: "t6_clasifica4", label: "Clasificación #4 (Idea → Propósito → Formato)", type: "text", required: false },
      { name: "t6_clasifica5", label: "Clasificación #5 (Idea → Propósito → Formato)", type: "text", required: false },
    ],
  },
  {
    id: "t7-indice",
    title: "7.1 Índice de Guiones",
    fields: [
      { name: "t7_indice1", label: "Guion #1 (idea, formato, gancho textual, gancho visual, CTA)", type: "text", required: false },
      { name: "t7_indice2", label: "Guion #2 (idea, formato, gancho textual, gancho visual, CTA)", type: "text", required: false },
      { name: "t7_indice3", label: "Guion #3 (idea, formato, gancho textual, gancho visual, CTA)", type: "text", required: false },
    ],
  },
  {
    id: "t7-guion1",
    title: "7.2 Guion Completo #1",
    fields: [
      { name: "t7_g1Fecha", label: "Fecha", type: "text", required: false },
      { name: "t7_g1Plataforma", label: "Plataforma", type: "select", required: false, options: [{ value: "instagram-reels", label: "Instagram Reels" }, { value: "tiktok", label: "TikTok" }, { value: "youtube", label: "YouTube" }] },
      { name: "t7_g1Pilar", label: "Pilar", type: "text", required: false },
      { name: "t7_g1Estructura", label: "Estructura usada", type: "text", required: false },
      { name: "t7_g1GanchoVerbal", label: "Gancho verbal (primeras 1-3 frases)", type: "textarea", required: false },
      { name: "t7_g1GanchoVisual", label: "Gancho visual (qué se ve en pantalla)", type: "textarea", required: false },
      { name: "t7_g1GanchoTextual", label: "Gancho textual (texto superpuesto)", type: "textarea", required: false },
      { name: "t7_g1Desarrollo", label: "Desarrollo", type: "textarea", required: false },
      { name: "t7_g1Cta", label: "CTA", type: "text", required: false },
      { name: "t7_g1Resultado", label: "Resultado (llenar después de publicar)", type: "textarea", required: false },
      { name: "t7_g1Notas", label: "Notas de mejora", type: "textarea", required: false },
    ],
  },
  {
    id: "t7-guion2",
    title: "7.2 Guion Completo #2",
    fields: [
      { name: "t7_g2Fecha", label: "Fecha", type: "text", required: false },
      { name: "t7_g2Plataforma", label: "Plataforma", type: "select", required: false, options: [{ value: "instagram-reels", label: "Instagram Reels" }, { value: "tiktok", label: "TikTok" }, { value: "youtube", label: "YouTube" }] },
      { name: "t7_g2Pilar", label: "Pilar", type: "text", required: false },
      { name: "t7_g2Estructura", label: "Estructura usada", type: "text", required: false },
      { name: "t7_g2GanchoVerbal", label: "Gancho verbal (primeras 1-3 frases)", type: "textarea", required: false },
      { name: "t7_g2GanchoVisual", label: "Gancho visual (qué se ve en pantalla)", type: "textarea", required: false },
      { name: "t7_g2GanchoTextual", label: "Gancho textual (texto superpuesto)", type: "textarea", required: false },
      { name: "t7_g2Desarrollo", label: "Desarrollo", type: "textarea", required: false },
      { name: "t7_g2Cta", label: "CTA", type: "text", required: false },
      { name: "t7_g2Resultado", label: "Resultado (llenar después de publicar)", type: "textarea", required: false },
      { name: "t7_g2Notas", label: "Notas de mejora", type: "textarea", required: false },
    ],
  },
  {
    id: "t7-guion3",
    title: "7.2 Guion Completo #3",
    fields: [
      { name: "t7_g3Fecha", label: "Fecha", type: "text", required: false },
      { name: "t7_g3Plataforma", label: "Plataforma", type: "select", required: false, options: [{ value: "instagram-reels", label: "Instagram Reels" }, { value: "tiktok", label: "TikTok" }, { value: "youtube", label: "YouTube" }] },
      { name: "t7_g3Pilar", label: "Pilar", type: "text", required: false },
      { name: "t7_g3Estructura", label: "Estructura usada", type: "text", required: false },
      { name: "t7_g3GanchoVerbal", label: "Gancho verbal (primeras 1-3 frases)", type: "textarea", required: false },
      { name: "t7_g3GanchoVisual", label: "Gancho visual (qué se ve en pantalla)", type: "textarea", required: false },
      { name: "t7_g3GanchoTextual", label: "Gancho textual (texto superpuesto)", type: "textarea", required: false },
      { name: "t7_g3Desarrollo", label: "Desarrollo", type: "textarea", required: false },
      { name: "t7_g3Cta", label: "CTA", type: "text", required: false },
      { name: "t7_g3Resultado", label: "Resultado (llenar después de publicar)", type: "textarea", required: false },
      { name: "t7_g3Notas", label: "Notas de mejora", type: "textarea", required: false },
    ],
  },
  {
    id: "t7-brandvoice",
    title: "7.3 Brand Voice para IA",
    fields: [
      { name: "t7_contextoMarca", label: "Tu contexto de marca en una línea", type: "textarea", required: false },
      { name: "t7_palabrasCaracteristicas", label: "Tus palabras o frases características", type: "textarea", required: false },
      { name: "t7_tonoPrincipal", label: "Tu tono principal", type: "select", required: false, options: [{ value: "cercano", label: "Cercano" }, { value: "directo", label: "Directo" }, { value: "educativo", label: "Educativo" }, { value: "inspirador", label: "Inspirador" }, { value: "con-humor", label: "Con humor" }, { value: "otro", label: "Otro" }] },
      { name: "t7_brandVoiceResultado", label: "Pegá acá el resultado final del Brand Voice (si ya lo generaste con IA)", type: "textarea", required: false },
    ],
  },
  {
    id: "t7-video1",
    title: "7.4 Análisis de Viralidad — Video #1",
    description: "Buscá un video de más de 100k vistas en tu nicho y completá la ficha",
    fields: [
      { name: "t7_v1Cuenta", label: "Cuenta / URL", type: "text", required: false },
      { name: "t7_v1GanchoVerbal", label: "Gancho verbal (primeras 3 segundos)", type: "textarea", required: false },
      { name: "t7_v1GanchoVisual", label: "Gancho visual (qué se ve en pantalla)", type: "textarea", required: false },
      { name: "t7_v1GanchoTextual", label: "Gancho textual (texto superpuesto)", type: "textarea", required: false },
      { name: "t7_v1Estructura", label: "Estructura usada", type: "textarea", required: false },
      { name: "t7_v1PorQue", label: "Por qué creés que funcionó", type: "textarea", required: false },
    ],
  },
  {
    id: "t7-video2",
    title: "7.4 Análisis de Viralidad — Video #2",
    description: "Buscá un video de más de 100k vistas en tu nicho y completá la ficha",
    fields: [
      { name: "t7_v2Cuenta", label: "Cuenta / URL", type: "text", required: false },
      { name: "t7_v2GanchoVerbal", label: "Gancho verbal (primeras 3 segundos)", type: "textarea", required: false },
      { name: "t7_v2GanchoVisual", label: "Gancho visual (qué se ve en pantalla)", type: "textarea", required: false },
      { name: "t7_v2GanchoTextual", label: "Gancho textual (texto superpuesto)", type: "textarea", required: false },
      { name: "t7_v2Estructura", label: "Estructura usada", type: "textarea", required: false },
      { name: "t7_v2PorQue", label: "Por qué creés que funcionó", type: "textarea", required: false },
    ],
  },
  {
    id: "t7-video3",
    title: "7.4 Análisis de Viralidad — Video #3",
    description: "Buscá un video de más de 100k vistas en tu nicho y completá la ficha",
    fields: [
      { name: "t7_v3Cuenta", label: "Cuenta / URL", type: "text", required: false },
      { name: "t7_v3GanchoVerbal", label: "Gancho verbal (primeras 3 segundos)", type: "textarea", required: false },
      { name: "t7_v3GanchoVisual", label: "Gancho visual (qué se ve en pantalla)", type: "textarea", required: false },
      { name: "t7_v3GanchoTextual", label: "Gancho textual (texto superpuesto)", type: "textarea", required: false },
      { name: "t7_v3Estructura", label: "Estructura usada", type: "textarea", required: false },
      { name: "t7_v3PorQue", label: "Por qué creés que funcionó", type: "textarea", required: false },
    ],
  },
  {
    id: "t7-patrones",
    title: "7.4 Patrones Identificados en mi Nicho",
    fields: [
      { name: "t7_patronGanchoVerbal", label: "Tipo de gancho verbal que más se repite", type: "textarea", required: false },
      { name: "t7_patronGanchoVisual", label: "Tipo de gancho visual que más se repite", type: "textarea", required: false },
      { name: "t7_caracteristicasComunes", label: "Características comunes en las estructuras de guion", type: "textarea", required: false },
      { name: "t7_patronesIncorporar", label: "Patrones que VOS querés incorporar", type: "textarea", required: false },
    ],
  },
  {
    id: "t7-estructuras",
    title: "7.4.1 Mis Estructuras de Guion",
    fields: [
      { name: "t7_e1CuandoUso", label: "Estructura #1 — Cuándo la usás", type: "text", required: false },
      { name: "t7_e1Ejemplo", label: "Estructura #1 — Ejemplo de guion tuyo que la usó", type: "textarea", required: false },
      { name: "t7_e2CuandoUso", label: "Estructura #2 — Cuándo la usás", type: "text", required: false },
      { name: "t7_e2Ejemplo", label: "Estructura #2 — Ejemplo de guion tuyo que la usó", type: "textarea", required: false },
      { name: "t7_e3CuandoUso", label: "Estructura #3 — Cuándo la usás", type: "text", required: false },
      { name: "t7_e3Ejemplo", label: "Estructura #3 — Ejemplo de guion tuyo que la usó", type: "textarea", required: false },
      { name: "t7_estructuraFavorita", label: "Tu estructura favorita hasta ahora", type: "text", required: false },
      { name: "t7_estructuraFavoritaPorque", label: "Por qué", type: "textarea", required: false },
    ],
  },
  {
    id: "t7-formula-gancho",
    title: "7.5.1 La Fórmula del Gancho Verbal",
    fields: [
      { name: "t7_tipoGanchoMejor", label: "Tipo de gancho que mejor te funciona (pregunta / dato / confesión / afirmación)", type: "text", required: false },
      { name: "t7_gancho1", label: "Tus 5 mejores ganchos verbales creados — #1", type: "text", required: false },
      { name: "t7_gancho2", label: "Tus 5 mejores ganchos verbales creados — #2", type: "text", required: false },
      { name: "t7_gancho3", label: "Tus 5 mejores ganchos verbales creados — #3", type: "text", required: false },
      { name: "t7_gancho4", label: "Tus 5 mejores ganchos verbales creados — #4", type: "text", required: false },
      { name: "t7_gancho5", label: "Tus 5 mejores ganchos verbales creados — #5", type: "text", required: false },
    ],
  },
  {
    id: "t7-enc",
    title: "7.5.2 Forma en F y Sistema E.N.C.",
    fields: [
      { name: "t7_estimuloNucleo", label: "Tu patrón ganador analizado con el sistema E.N.C. — Estímulo núcleo", type: "textarea", required: false },
      { name: "t7_nivelCargaCognitiva", label: "Nivel de carga cognitiva", type: "textarea", required: false },
      { name: "t7_contextoENC", label: "Contexto", type: "textarea", required: false },
      { name: "t7_ejemploGanchoVisual", label: "Ejemplo de gancho visual que harás", type: "textarea", required: false },
    ],
  },
  {
    id: "t7-formas-visuales",
    title: "7.5.3 Las 5 Formas Visuales",
    fields: [
      { name: "t7_formaVisual", label: "Forma visual que usarás", type: "text", required: false },
      { name: "t7_comoAplicoFormaVisual", label: "Cómo la aplicás en tu nicho", type: "textarea", required: false },
    ],
  },
  {
    id: "t7-bot-ganchos",
    title: "7.5.4 Bot de Ganchos Visuales",
    fields: [
      { name: "t7_botGancho1", label: "Gancho visual #1 que el bot te generó y querés usar", type: "text", required: false },
      { name: "t7_botGancho2", label: "Gancho visual #2 que el bot te generó y querés usar", type: "text", required: false },
      { name: "t7_botGancho3", label: "Gancho visual #3 que el bot te generó y querés usar", type: "text", required: false },
    ],
  },
  {
    id: "t7-ganchos-estrategicos",
    title: "7.5.5 Cómo Analizás y Diseñás tus Ganchos",
    fields: [
      { name: "t7_referenciaAnalizo", label: "Referencia que analizás antes de crear (qué cuenta, hashtag o video)", type: "textarea", required: false },
      { name: "t7_mejorGanchoVisual1", label: "Tus 3 mejores ganchos visuales hasta ahora — #1", type: "text", required: false },
      { name: "t7_mejorGanchoVisual2", label: "Tus 3 mejores ganchos visuales hasta ahora — #2", type: "text", required: false },
      { name: "t7_mejorGanchoVisual3", label: "Tus 3 mejores ganchos visuales hasta ahora — #3", type: "text", required: false },
    ],
  },
  {
    id: "t7-ctas",
    title: "7.6 Banco de CTAs (por plataforma y objetivo)",
    fields: [
      { name: "t7_ctaReels", label: "CTA para Reels / TikTok", type: "text", required: false },
      { name: "t7_ctaCarruseles", label: "CTA para Carruseles", type: "text", required: false },
      { name: "t7_ctaHistorias", label: "CTA para Historias", type: "text", required: false },
      { name: "t7_ctaComentarios", label: "CTA para generar comentarios", type: "text", required: false },
      { name: "t7_ctaGuardados", label: "CTA para generar guardados", type: "text", required: false },
      { name: "t7_ctaDms", label: "CTA para generar DMs / leads", type: "text", required: false },
      { name: "t7_ctaVentaDirecta", label: "CTA para venta directa", type: "text", required: false },
      { name: "t7_ctaEfectivo1", label: "Tu CTA #1 más efectivo", type: "text", required: false },
      { name: "t7_ctaEfectivo1Resultado", label: "Resultado / respuesta que generó", type: "text", required: false },
      { name: "t7_ctaEfectivo2", label: "Tu CTA #2 más efectivo", type: "text", required: false },
      { name: "t7_ctaEfectivo2Resultado", label: "Resultado / respuesta que generó", type: "text", required: false },
    ],
  },
  {
    id: "t8-regla",
    title: "8.1 Regla del Calendario",
    fields: [
      { name: "t8_frecuenciaPublicacion", label: "Frecuencia de publicación semanal elegida", type: "text", required: false },
      { name: "t8_mejorHorario", label: "Mejor horario de publicación (según tus métricas)", type: "text", required: false },
    ],
  },
  {
    id: "t8-semana",
    title: "8.2 Semana Actual",
    description: "Idea/título, formato y ganchos por día",
    fields: [
      { name: "t8_semanaLunes", label: "Lunes — idea, nivel de energía, formato y ganchos", type: "text", required: false },
      { name: "t8_semanaMartes", label: "Martes — idea, nivel de energía, formato y ganchos", type: "text", required: false },
      { name: "t8_semanaMiercoles", label: "Miércoles — idea, nivel de energía, formato y ganchos", type: "text", required: false },
      { name: "t8_semanaJueves", label: "Jueves — idea, nivel de energía, formato y ganchos", type: "text", required: false },
      { name: "t8_semanaViernes", label: "Viernes — idea, nivel de energía, formato y ganchos", type: "text", required: false },
      { name: "t8_semanaSabado", label: "Sábado — idea, nivel de energía, formato y ganchos", type: "text", required: false },
      { name: "t8_semanaDomingo", label: "Domingo — idea, nivel de energía, formato y ganchos", type: "text", required: false },
    ],
  },
  {
    id: "t8-pipeline",
    title: "8.3 Ideas en Pipeline (próximas 2 semanas)",
    fields: [
      { name: "t8_pipeline1", label: "Idea en pipeline #1 (idea, formato, prioridad)", type: "text", required: false },
      { name: "t8_pipeline2", label: "Idea en pipeline #2 (idea, formato, prioridad)", type: "text", required: false },
      { name: "t8_pipeline3", label: "Idea en pipeline #3 (idea, formato, prioridad)", type: "text", required: false },
    ],
  },
  {
    id: "t9-indice",
    title: "9.1 Índice de Carruseles",
    fields: [
      { name: "t9_indice1", label: "Carrusel #1 (tema, estilo, tipo, resultado)", type: "text", required: false },
      { name: "t9_indice2", label: "Carrusel #2 (tema, estilo, tipo, resultado)", type: "text", required: false },
    ],
  },
  {
    id: "t9-carrusel1",
    title: "9.2 Carrusel Completo #1",
    fields: [
      { name: "t9_c1Tema", label: "Tema", type: "text", required: false },
      { name: "t9_c1Estilo", label: "Estilo de carrusel usado", type: "text", required: false },
      { name: "t9_c1Tipo", label: "Tipo", type: "select", required: false, options: [{ value: "viral", label: "Viral" }, { value: "valor", label: "Valor" }, { value: "venta", label: "Venta" }] },
      { name: "t9_c1Referencia", label: "Referencia visual (cuenta que inspiró el formato)", type: "text", required: false },
      { name: "t9_c1Slides", label: "Guion completo, slide por slide (texto principal y elemento visual de cada uno)", type: "textarea", required: false },
      { name: "t9_c1Resultado", label: "Resultado (llenar después de publicar)", type: "textarea", required: false },
    ],
  },
  {
    id: "t9-carrusel2",
    title: "9.2 Carrusel Completo #2",
    fields: [
      { name: "t9_c2Tema", label: "Tema", type: "text", required: false },
      { name: "t9_c2Estilo", label: "Estilo de carrusel usado", type: "text", required: false },
      { name: "t9_c2Tipo", label: "Tipo", type: "select", required: false, options: [{ value: "viral", label: "Viral" }, { value: "valor", label: "Valor" }, { value: "venta", label: "Venta" }] },
      { name: "t9_c2Referencia", label: "Referencia visual (cuenta que inspiró el formato)", type: "text", required: false },
      { name: "t9_c2Slides", label: "Guion completo, slide por slide (texto principal y elemento visual de cada uno)", type: "textarea", required: false },
      { name: "t9_c2Resultado", label: "Resultado (llenar después de publicar)", type: "textarea", required: false },
    ],
  },
  {
    id: "t10-definicion",
    title: "10.1 Definición del Lead Magnet",
    fields: [
      { name: "t10_nombre", label: "Nombre del lead magnet", type: "text", required: false },
      { name: "t10_promesa", label: "Promesa principal (qué aprenden / obtienen)", type: "textarea", required: false },
      { name: "t10_formato", label: "Formato", type: "select", required: false, options: [{ value: "pdf", label: "PDF" }, { value: "video", label: "Video" }, { value: "audio", label: "Audio" }, { value: "plantilla", label: "Plantilla" }, { value: "bot", label: "Bot" }, { value: "mini-curso", label: "Mini curso" }] },
      { name: "t10_tiempoConsumo", label: "Tiempo de consumo", type: "text", required: false },
      { name: "t10_dolorResponde", label: "¿A qué dolor del avatar responde?", type: "textarea", required: false },
      { name: "t10_comoConecta", label: "¿Cómo conecta con la oferta principal?", type: "textarea", required: false },
      { name: "t10_enlace", label: "Enlace al lead magnet (si ya existe)", type: "text", required: false },
    ],
  },
  {
    id: "t10-metricas",
    title: "10.2 Métricas del Lead Magnet",
    description: "Llenar después de tenerlo activo",
    fields: [
      { name: "t10_cuantasPedido", label: "Cuántas personas lo han pedido", type: "text", required: false },
      { name: "t10_conversion", label: "Conversión a compra (aprox.)", type: "text", required: false },
      { name: "t10_ajustes", label: "Ajustes realizados", type: "textarea", required: false },
    ],
  },
  {
    id: "t11-urgencia",
    title: "11.2 Secuencia URGENCIA",
    description: "Para activar decisión inmediata: FOMO, deadline, cierre de carrito, cupos limitados",
    fields: [
      { name: "t11_urgS1", label: "Story 1 — Situación de urgencia", type: "textarea", required: false },
      { name: "t11_urgS2", label: "Story 2 — Prueba breve (testimonio)", type: "textarea", required: false },
      { name: "t11_urgS3", label: "Story 3 — Detalle concreto de urgencia", type: "textarea", required: false },
      { name: "t11_urgS4", label: "Story 4 — CTA clara", type: "textarea", required: false },
      { name: "t11_urgS5", label: "Story 5 (opcional) — Recordatorio final", type: "textarea", required: false },
    ],
  },
  {
    id: "t11-oneshot-polls-libre",
    title: "11.2 Secuencias ONE SHOT, POLLS y LIBRE",
    fields: [
      { name: "t11_oneShotS1", label: "ONE SHOT — Story 1: Impacto visual (el resultado)", type: "textarea", required: false },
      { name: "t11_pollsS1", label: "POLLS — Story 1: Identificación (encuesta)", type: "textarea", required: false },
      { name: "t11_pollsS2", label: "POLLS — Story 2: Segunda encuesta / profundización", type: "textarea", required: false },
      { name: "t11_pollsS3", label: "POLLS — Story 3+: Profundización y CTA estratégica", type: "textarea", required: false },
      { name: "t11_libreS1", label: "LIBRE/LIFESTYLE — Story 1: Escena real (lo que estás haciendo)", type: "textarea", required: false },
      { name: "t11_libreS2", label: "LIBRE/LIFESTYLE — Story 2: Micro enseñanza (tip o reflexión)", type: "textarea", required: false },
    ],
  },
  {
    id: "t11-leadmagnet-seq",
    title: "11.2 Secuencia LEAD MAGNET",
    fields: [
      { name: "t11_lmNombreRecurso", label: "Nombre del recurso a entregar", type: "text", required: false },
      { name: "t11_lmS1", label: "Story 1 — Presentación del recurso", type: "textarea", required: false },
      { name: "t11_lmS2", label: "Story 2 — Para quién es y por qué vale la pena", type: "textarea", required: false },
      { name: "t11_lmS3", label: "Story 3 — Cómo pedirlo (CTA)", type: "textarea", required: false },
      { name: "t11_lmPalabraClave", label: "Palabra clave de activación", type: "text", required: false },
    ],
  },
  {
    id: "t11-banco-ideas",
    title: "11.3 Banco de Ideas para Historias Diarias",
    fields: [
      { name: "t11_ideaHistoria1", label: "Idea #1 para historia (idea, tipo: educar/entretener/vender, CTA)", type: "text", required: false },
      { name: "t11_ideaHistoria2", label: "Idea #2 para historia (idea, tipo: educar/entretener/vender, CTA)", type: "text", required: false },
      { name: "t11_ideaHistoria3", label: "Idea #3 para historia (idea, tipo: educar/entretener/vender, CTA)", type: "text", required: false },
    ],
  },
  {
    id: "t12-apertura",
    title: "12.1 Apertura de Conversación",
    fields: [
      { name: "t12_apertura1", label: "Apertura #1 (de dónde sale la conversación, mensaje de apertura, respuesta típica, ¿funciona?)", type: "textarea", required: false },
      { name: "t12_apertura2", label: "Apertura #2 (de dónde sale la conversación, mensaje de apertura, respuesta típica, ¿funciona?)", type: "textarea", required: false },
      { name: "t12_apertura3", label: "Apertura #3 (de dónde sale la conversación, mensaje de apertura, respuesta típica, ¿funciona?)", type: "textarea", required: false },
    ],
  },
  {
    id: "t12-objeciones",
    title: "12.2 Manejo de Objeciones",
    fields: [
      { name: "t12_objecion1", label: "Objeción #1 (objeción, tu respuesta, ¿funciona?, notas de mejora)", type: "textarea", required: false },
      { name: "t12_objecion2", label: "Objeción #2 (objeción, tu respuesta, ¿funciona?, notas de mejora)", type: "textarea", required: false },
      { name: "t12_objecion3", label: "Objeción #3 (objeción, tu respuesta, ¿funciona?, notas de mejora)", type: "textarea", required: false },
    ],
  },
  {
    id: "t12-testimonios",
    title: "12.3 Los Testimonios que te Hacen Vender",
    fields: [
      { name: "t12_numeroCasos", label: "Número de casos de éxito", type: "text", required: false },
      { name: "t12_transformacion", label: "Transformación que logran", type: "textarea", required: false },
      { name: "t12_caso1ComoLlego", label: "Caso de éxito 1 — ¿Cómo llegó?", type: "textarea", required: false },
      { name: "t12_caso1Victoria", label: "Caso de éxito 1 — Su victoria resumida en 1 línea", type: "text", required: false },
      { name: "t12_caso2ComoLlego", label: "Caso de éxito 2 — ¿Cómo llegó?", type: "textarea", required: false },
      { name: "t12_caso2Victoria", label: "Caso de éxito 2 — Su victoria resumida en 1 línea", type: "text", required: false },
      { name: "t12_caso3ComoLlego", label: "Caso de éxito 3 — ¿Cómo llegó?", type: "textarea", required: false },
      { name: "t12_caso3Victoria", label: "Caso de éxito 3 — Su victoria resumida en 1 línea", type: "text", required: false },
    ],
  },
  {
    id: "t13-ctas-formato",
    title: "13.1 CTAs por Formato",
    fields: [
      { name: "t13_ctaReelsDetalle", label: "CTAs para Reels/TikToks que probaste (CTA, contexto de uso, cuántos comentarios genera)", type: "textarea", required: false },
      { name: "t13_ctaCarruselesDetalle", label: "CTAs para Carruseles que probaste (CTA, contexto de uso, cuántos comentarios genera)", type: "textarea", required: false },
      { name: "t13_ctaHistoriasDetalle", label: "CTAs para Historias que probaste (CTA, contexto de uso, cuántos comentarios genera)", type: "textarea", required: false },
    ],
  },
  {
    id: "t13-top-ctas",
    title: "13.2 Los 2 CTAs que Más te Funcionan",
    fields: [
      { name: "t13_ctaTop1", label: "CTA #1", type: "text", required: false },
      { name: "t13_ctaTop1PorQue", label: "Por qué funciona", type: "text", required: false },
      { name: "t13_ctaTop2", label: "CTA #2", type: "text", required: false },
      { name: "t13_ctaTop2PorQue", label: "Por qué funciona", type: "text", required: false },
    ],
  },
  {
    id: "t14-competencia",
    title: "14.1 Investigación de Competencia",
    fields: [
      { name: "t14_competidor1", label: "Competidor #1 (nombre, ángulo que usa, gancho que usa, qué lo hace efectivo)", type: "textarea", required: false },
      { name: "t14_competidor2", label: "Competidor #2 (nombre, ángulo que usa, gancho que usa, qué lo hace efectivo)", type: "textarea", required: false },
      { name: "t14_competidor3", label: "Competidor #3 (nombre, ángulo que usa, gancho que usa, qué lo hace efectivo)", type: "textarea", required: false },
    ],
  },
  {
    id: "t14-angulos",
    title: "14.2 Mis Ángulos de Venta",
    fields: [
      { name: "t14_angulo1", label: "Ángulo #1 (ángulo, dolor del avatar que aborda, prioridad para probar)", type: "textarea", required: false },
      { name: "t14_angulo2", label: "Ángulo #2 (ángulo, dolor del avatar que aborda, prioridad para probar)", type: "textarea", required: false },
      { name: "t14_angulo3", label: "Ángulo #3 (ángulo, dolor del avatar que aborda, prioridad para probar)", type: "textarea", required: false },
    ],
  },
  {
    id: "t14-anuncio1",
    title: "14.3 Guion de Anuncio #1",
    fields: [
      { name: "t14_ad1Angulo", label: "Ángulo", type: "text", required: false },
      { name: "t14_ad1Formato", label: "Formato", type: "select", required: false, options: [{ value: "video", label: "Video" }, { value: "imagen", label: "Imagen" }, { value: "carrusel", label: "Carrusel" }] },
      { name: "t14_ad1Gancho", label: "Gancho (primeras 3 segundos / primera línea)", type: "textarea", required: false },
      { name: "t14_ad1Desarrollo", label: "Desarrollo", type: "textarea", required: false },
      { name: "t14_ad1Cta", label: "CTA", type: "text", required: false },
      { name: "t14_ad1Metricas", label: "Métricas (llenar cuando esté activo: CTR / CPL / ROAS)", type: "text", required: false },
    ],
  },
  {
    id: "t14-anuncio2",
    title: "14.3 Guion de Anuncio #2",
    fields: [
      { name: "t14_ad2Angulo", label: "Ángulo", type: "text", required: false },
      { name: "t14_ad2Formato", label: "Formato", type: "select", required: false, options: [{ value: "video", label: "Video" }, { value: "imagen", label: "Imagen" }, { value: "carrusel", label: "Carrusel" }] },
      { name: "t14_ad2Gancho", label: "Gancho (primeras 3 segundos / primera línea)", type: "textarea", required: false },
      { name: "t14_ad2Desarrollo", label: "Desarrollo", type: "textarea", required: false },
      { name: "t14_ad2Cta", label: "CTA", type: "text", required: false },
      { name: "t14_ad2Metricas", label: "Métricas (llenar cuando esté activo: CTR / CPL / ROAS)", type: "text", required: false },
    ],
  },
  {
    id: "t14-anuncio3",
    title: "14.3 Guion de Anuncio #3",
    fields: [
      { name: "t14_ad3Angulo", label: "Ángulo", type: "text", required: false },
      { name: "t14_ad3Formato", label: "Formato", type: "select", required: false, options: [{ value: "video", label: "Video" }, { value: "imagen", label: "Imagen" }, { value: "carrusel", label: "Carrusel" }] },
      { name: "t14_ad3Gancho", label: "Gancho (primeras 3 segundos / primera línea)", type: "textarea", required: false },
      { name: "t14_ad3Desarrollo", label: "Desarrollo", type: "textarea", required: false },
      { name: "t14_ad3Cta", label: "CTA", type: "text", required: false },
      { name: "t14_ad3Metricas", label: "Métricas (llenar cuando esté activo: CTR / CPL / ROAS)", type: "text", required: false },
    ],
  },
  {
    id: "t15-setup",
    title: "15.1 Setup Inicial",
    fields: [
      { name: "t15_pixelInstalado", label: "Pixel de Meta instalado", type: "select", required: false, options: [{ value: "si", label: "Sí" }, { value: "no", label: "No" }] },
      { name: "t15_dominioVerificado", label: "Dominio verificado", type: "select", required: false, options: [{ value: "si", label: "Sí" }, { value: "no", label: "No" }] },
      { name: "t15_cuentaAnuncios", label: "Cuenta de anuncios", type: "text", required: false },
      { name: "t15_objetivoPrincipal", label: "Objetivo principal de las campañas", type: "select", required: false, options: [{ value: "leads", label: "Leads" }, { value: "ventas", label: "Ventas" }, { value: "trafico", label: "Tráfico" }, { value: "seguidores", label: "Seguidores" }] },
    ],
  },
  {
    id: "t15-activas",
    title: "15.2 Campañas Activas",
    fields: [
      { name: "t15_campana1", label: "Campaña #1 (nombre, objetivo, público, presupuesto diario, fecha de inicio)", type: "textarea", required: false },
      { name: "t15_campana2", label: "Campaña #2 (nombre, objetivo, público, presupuesto diario, fecha de inicio)", type: "textarea", required: false },
    ],
  },
  {
    id: "t15-metricas-aprendizajes",
    title: "15.3-15.4 Métricas y Aprendizajes de Campañas",
    fields: [
      { name: "t15_metricasNotas", label: "Resumen de tus métricas de campañas hasta ahora (inversión, CPL, CTR, leads, ventas, ROAS)", type: "textarea", required: false },
      { name: "t15_aprendizajes", label: "Aprendizajes de campañas (qué cambiaste, por qué, si funcionó)", type: "textarea", required: false },
    ],
  },
  {
    id: "t16-analisis",
    title: "16.1-16.3 Análisis y Decisiones",
    fields: [
      { name: "t16_analisisSemanal", label: "Análisis semanal de contenido (video con más alcance, mejor retención, más conversiones, insight clave)", type: "textarea", required: false },
      { name: "t16_videosResucitar", label: "Banco de videos a resucitar (video, fecha original, por qué funcionó, qué cambio harías)", type: "textarea", required: false },
      { name: "t16_planAccion", label: "Tu plan de acción después de ver las métricas", type: "textarea", required: false },
    ],
  },
  {
    id: "t16-patrones",
    title: "16.4 Patrones Identificados",
    fields: [
      { name: "t16_ganchosFuncionan", label: "Qué tipos de gancho te funcionan mejor", type: "textarea", required: false },
      { name: "t16_estructurasRetencion", label: "Qué estructuras de guion dan más retención", type: "textarea", required: false },
      { name: "t16_diasHorarios", label: "Qué días/horarios tienen más alcance", type: "textarea", required: false },
      { name: "t16_formatosSeguidores", label: "Qué formatos convierten más a seguidores", type: "textarea", required: false },
      { name: "t16_formatosClientes", label: "Qué formatos convierten más a clientes", type: "textarea", required: false },
    ],
  },
  {
    id: "t17-estrategia",
    title: "17.1 Estrategia de YouTube",
    fields: [
      { name: "t17_esParteEstrategia", label: "¿YouTube es parte de tu estrategia?", type: "select", required: false, options: [{ value: "si", label: "Sí" }, { value: "no", label: "No" }, { value: "futuro", label: "Futuro" }] },
      { name: "t17_formatoElegido", label: "Formato elegido para YouTube", type: "select", required: false, options: [{ value: "vlogs", label: "Vlogs" }, { value: "tutoriales", label: "Tutoriales" }, { value: "entrevistas", label: "Entrevistas" }, { value: "shorts", label: "Shorts" }, { value: "otro", label: "Otro" }] },
      { name: "t17_frecuencia", label: "Frecuencia de publicación", type: "select", required: false, options: [{ value: "semanal", label: "Semanal" }, { value: "quincenal", label: "Quincenal" }, { value: "mensual", label: "Mensual" }] },
    ],
  },
  {
    id: "t17-ideas",
    title: "17.2 Ideas Validadas para YouTube",
    fields: [
      { name: "t17_idea1", label: "Idea #1 (idea/tema, título propuesto, concepto de miniatura, palabras clave)", type: "textarea", required: false },
      { name: "t17_idea2", label: "Idea #2 (idea/tema, título propuesto, concepto de miniatura, palabras clave)", type: "textarea", required: false },
      { name: "t17_idea3", label: "Idea #3 (idea/tema, título propuesto, concepto de miniatura, palabras clave)", type: "textarea", required: false },
    ],
  },
  {
    id: "t18-prompts",
    title: "18. Mis Prompts y Procesos Favoritos (opcional)",
    description: "Tu biblioteca de prompts de IA que ya te funcionaron, por categoría",
    fields: [
      { name: "t18_promptsGuionizacion", label: "Prompts favoritos para Guionización (proceso, propósito, resultado, prompt base)", type: "textarea", required: false },
      { name: "t18_promptsGanchos", label: "Prompts favoritos para Ganchos", type: "textarea", required: false },
      { name: "t18_promptsCarruseles", label: "Prompts favoritos para Carruseles", type: "textarea", required: false },
      { name: "t18_promptsHistorias", label: "Prompts favoritos para Historias", type: "textarea", required: false },
      { name: "t18_promptsInvestigacion", label: "Prompts favoritos para Investigación", type: "textarea", required: false },
      { name: "t18_promptsAds", label: "Prompts favoritos para Ads", type: "textarea", required: false },
      { name: "t18_promptsIAGenerativa", label: "Prompts favoritos de IA generativa (Higgsfield / Gemini / Nanobanana)", type: "textarea", required: false },
    ],
  },
  {
    id: "t19-oferta",
    title: "19.1-19.2 Nombre de la Oferta y Promesa",
    fields: [
      { name: "t19_nombreOferta", label: "Nombre oficial del programa/masterclass/entrenamiento", type: "text", required: false },
      { name: "t19_promesaFormato", label: "Promesa principal — formato recomendado (Hoy, en X tiempo, vas a... y saldrás con... sin..., usando...)", type: "textarea", required: false },
      { name: "t19_promesaLanding", label: "Promesa principal — versión para landing (Resultado concreto en duración aunque objeción)", type: "textarea", required: false },
    ],
  },
  {
    id: "t19-acciones-entregables",
    title: "19.3-19.4 Acciones y Entregables",
    fields: [
      { name: "t19_accion1", label: "Qué harán hoy — Acción #1", type: "text", required: false },
      { name: "t19_accion2", label: "Qué harán hoy — Acción #2", type: "text", required: false },
      { name: "t19_accion3", label: "Qué harán hoy — Acción #3", type: "text", required: false },
      { name: "t19_accion4", label: "Qué harán hoy — Acción #4 (opcional)", type: "text", required: false },
      { name: "t19_entregable1", label: "Qué se llevan listos — Entregable #1", type: "text", required: false },
      { name: "t19_entregable2", label: "Qué se llevan listos — Entregable #2", type: "text", required: false },
      { name: "t19_entregable3", label: "Qué se llevan listos — Entregable #3", type: "text", required: false },
      { name: "t19_entregable4", label: "Qué se llevan listos — Entregable #4", type: "text", required: false },
    ],
  },
  {
    id: "t19-mecanismo",
    title: "19.5-19.6 Mecanismo Diferenciador y Objeción Central",
    fields: [
      { name: "t19_nombreSistema", label: "Nombre del sistema", type: "text", required: false },
      { name: "t19_descripcionSistema", label: "Cómo funciona tu método y qué lo vuelve único (en 1 frase)", type: "textarea", required: false },
      { name: "t19_objecionCentral", label: "Objeción central que neutralizás", type: "select", required: false, options: [{ value: "tiempo", label: "Tiempo" }, { value: "no-se-editar", label: "No sé editar / no sé grabar" }, { value: "no-tengo-audiencia", label: "No tengo audiencia" }, { value: "miedo-mostrarme", label: "Me da miedo mostrarme" }, { value: "no-se-vender", label: "No sé vender" }, { value: "no-entiendo-algoritmo", label: "No entiendo el algoritmo" }, { value: "tecnologia", label: "Tecnología / complejidad" }] },
      { name: "t19_textoObjecion", label: "Texto: \"En esta sesión eliminamos [objeción] porque [razón práctica]\"", type: "textarea", required: false },
    ],
  },
  {
    id: "t19-estructura",
    title: "19.7 Estructura de la Sesión",
    description: "Dividí en bloques de 5-20 minutos",
    fields: [
      { name: "t19_bloque1", label: "Bloque 1 — Nombre y qué se hará", type: "text", required: false },
      { name: "t19_bloque2", label: "Bloque 2 — Nombre y qué se ejecutará", type: "text", required: false },
      { name: "t19_bloque3", label: "Bloque 3 — Nombre y entrega del activo", type: "text", required: false },
      { name: "t19_bloque4", label: "Bloque 4 — Nombre y prueba mínima", type: "text", required: false },
      { name: "t19_bloque5", label: "Bloque 5 — Cierre + CTA: qué acción deben tomar después", type: "text", required: false },
    ],
  },
  {
    id: "t19-prueba-bonus",
    title: "19.8-19.9 Prueba Mínima y Bonus",
    fields: [
      { name: "t19_demo", label: "Demo en vivo (antes→después real / creación de un recurso en vivo / corrección de un ejemplo)", type: "textarea", required: false },
      { name: "t19_entregaExpress", label: "Entrega express (\"[Plantilla X] completada en directo\")", type: "text", required: false },
      { name: "t19_bonus1", label: "Bonus #1 (qué es + valor percibido)", type: "text", required: false },
      { name: "t19_bonus2", label: "Bonus #2 (qué es + valor percibido)", type: "text", required: false },
      { name: "t19_bonus3", label: "Bonus #3 (qué es + valor percibido)", type: "text", required: false },
    ],
  },
  {
    id: "t19-resumen",
    title: "19.10-19.13 Resultados y Resumen Final",
    fields: [
      { name: "t19_resultadosFinales", label: "Resultados finales esperables (\"Saldrás con...\", \"Tendrás listo...\")", type: "textarea", required: false },
      { name: "t19_contenidoPrograma", label: "Contenido del programa (tema/habilidad, aplicación, recurso entregado — en lista)", type: "textarea", required: false },
      { name: "t19_resumenFinal", label: "Resumen final en 1 párrafo para la landing / guion del pitch", type: "textarea", required: false },
      { name: "t19_reporteLanzamiento", label: "Notas del reporte de resultados del lanzamiento (si ya lo hiciste)", type: "textarea", required: false },
    ],
  },
];
