export const ENCUESTA_COMPLETA_INTRO = {
  title: "Encuesta Completa de Descubrimiento",
  subtitle: "Todo lo que necesitamos saber de tu proyecto, en un solo lugar",
  description:
    "Esta es la versión unificada: incluye las preguntas originales más las del Manual de Negocio (historia, avatar, oferta, competencia). Te va a tomar bastante más tiempo que la encuesta corta — podés ir guardando y volviendo por secciones.",
};

export const FORM_SECTIONS_COMPLETA = [
  {
    id: "datos-basicos",
    title: "Datos Básicos",
    description: "Empecemos con información sobre vos",
    fields: [
      { name: "nombre", label: "¿Cuál es tu nombre?", type: "text", required: true },
      { name: "edad", label: "¿Cuántos años tenés?", type: "text", required: true },
      { name: "ubicacion", label: "¿Dónde vivís actualmente?", type: "text", required: true },
      {
        name: "experiencia",
        label: "Contame tu experiencia previa. ¿Qué trabajos o proyectos relevantes has tenido?",
        type: "textarea",
        required: true,
        placeholder: "Ej: En Bariloche gestioné casas de alquiler...",
      },
    ],
  },
  {
    id: "negocio",
    title: "Sobre Tu Negocio",
    description: "Entendamos mejor la idea que tenés",
    fields: [
      {
        name: "tipoNegocio",
        label: "¿Qué tipo de negocio querés montar?",
        type: "select",
        required: true,
        options: [
          { value: "marketplace-propiedades", label: "Marketplace de propiedades en alquiler" },
          { value: "plataforma-gestion", label: "Plataforma de gestión de propiedades" },
          { value: "agencia-digital", label: "Agencia digital de alquileres" },
          { value: "otro", label: "Otro (especificá abajo)" },
        ],
      },
      {
        name: "modeloNegocio",
        label: "¿Cuál sería tu modelo de negocio? (Cómo ganarías dinero, comisiones, etc.)",
        type: "textarea",
        required: true,
        placeholder: "Ej: Cobrar comisión por cada reserva, suscripción mensual para anfitriones, etc.",
      },
      {
        name: "targetMarket",
        label: "¿Quiénes serían tus clientes? ¿Propietarios, inquilinos, ambos?",
        type: "textarea",
        required: true,
        placeholder: "Ej: Propietarios en Punta Alta que quieren alquilar temporada...",
      },
      {
        name: "barreras",
        label: "¿Cuáles ves que son las principales barreras o desafíos para llevar adelante este negocio?",
        type: "textarea",
        required: true,
        placeholder: "Ej: No tengo propiedades propias, desconocimiento legal, competencia, etc.",
      },
    ],
  },
  {
    id: "solucion-web",
    title: "Sobre la Solución Web",
    description: "Entender qué necesitás de la plataforma digital",
    fields: [
      {
        name: "tipoWeb",
        label: "¿Qué tipo de web buscás?",
        type: "select",
        required: true,
        options: [
          { value: "landing", label: "Landing page (solo presentación)" },
          { value: "marketplace", label: "Marketplace completo (listados + reservas)" },
          { value: "plataforma-gestion", label: "Plataforma de gestión interna" },
          { value: "hibrido", label: "Combinación (landing + funcionalidades básicas)" },
        ],
      },
      {
        name: "funcionalidades",
        label: "¿Cuáles serían las funcionalidades más importantes?",
        type: "textarea",
        required: true,
        placeholder: "Ej: Listado de propiedades, galería de fotos, sistema de reservas, pagos, reseñas, etc.",
      },
      {
        name: "presupuesto",
        label: "¿Cuál es tu rango de presupuesto aproximado? (en pesos ARS)",
        type: "select",
        required: true,
        options: [
          { value: "100-300k", label: "$100.000 a $300.000" },
          { value: "301-500k", label: "$301.000 a $500.000" },
          { value: "501-800k", label: "$501.000 a $800.000" },
          { value: "800-1100k", label: "$800.000 a $1.100.000" },
          { value: "1100k+", label: "Más de $1.100.000" },
          { value: "flexible", label: "Flexible (depende de lo que me proponjas)" },
        ],
      },
      {
        name: "timeline",
        label: "¿Cuándo querés que la web esté online funcionando?",
        type: "select",
        required: true,
        options: [
          { value: "asap", label: "Lo antes posible (urgente)" },
          { value: "1-2-meses", label: "1-2 meses" },
          { value: "2-3-meses", label: "2-3 meses" },
          { value: "flexible", label: "Flexible" },
        ],
      },
      {
        name: "ciudades",
        label: "¿De qué ciudades querés que se carguen propiedades?",
        type: "textarea",
        required: false,
        placeholder: "Ej: Punta Alta, Bahía Blanca, localidades cercanas...",
      },
      {
        name: "estrategiaMarketing",
        label: "¿Cómo esperas que la gente de Argentina conozca esta web para ingresar a buscar propiedades?",
        type: "textarea",
        required: false,
        placeholder: "Ej: Redes sociales, publicidad pagada, boca en boca, Google Ads, etc.",
      },
      {
        name: "redesSociales",
        label: "¿Querés que la web tenga redes sociales?",
        type: "select",
        required: false,
        options: [
          { value: "si", label: "Sí, quiero presencia en redes" },
          { value: "no", label: "No, por ahora solo la web" },
          { value: "indeciso", label: "Indeciso, depende de lo que me propongas" },
        ],
      },
      {
        name: "gestorContenido",
        label: "¿Buscas que alguien te gestione el contenido de las redes sociales?",
        type: "select",
        required: false,
        options: [
          { value: "si", label: "Sí, necesito gestor de contenido" },
          { value: "no", label: "No, yo lo manejo" },
          { value: "flexible", label: "Flexible" },
        ],
      },
    ],
  },
  {
    id: "expectativas",
    title: "Expectativas y Comunicación",
    description: "¿Cómo te gustaría trabajar con nosotros?",
    fields: [
      {
        name: "motivacion",
        label: "¿Por qué es importante para vos armar este negocio? ¿Qué te motiva?",
        type: "textarea",
        required: true,
        placeholder: "Ej: Quiero ser independiente, generar ingresos pasivos, ayudar a propietarios, etc.",
      },
      {
        name: "comunicacion",
        label: "¿Cómo preferís comunicarte? (Reuniones, mensajes, email, etc.)",
        type: "select",
        required: true,
        options: [
          { value: "llamadas", label: "Reuniones por video/llamada" },
          { value: "whatsapp", label: "WhatsApp + reuniones puntuales" },
          { value: "email", label: "Email (más formal)" },
          { value: "flexible", label: "Lo que sea más fácil" },
        ],
      },
      {
        name: "observaciones",
        label: "¿Hay algo más que quieras que sepa Fernando antes de la reunión?",
        type: "textarea",
        required: false,
        placeholder: "Observaciones, dudas, referencias, cualquier cosa relevante...",
      },
    ],
  },
  {
    id: "punto-partida",
    title: "Punto de Partida: Tu Situación Hoy",
    description: "¿Ya existe algo concreto para vender u ofrecer hoy? Esto define qué preguntas te hacemos.",
    fields: [
      {
        name: "existeAlgoParaVender",
        label: "¿Ya existe algo concreto para vender u ofrecer hoy? (algo que, si un propietario o huésped preguntara hoy, se le pueda cobrar u ofrecer)",
        type: "select",
        required: true,
        options: [
          { value: "si", label: "Sí, ya tengo algo funcionando (aunque sea a mano)" },
          { value: "no", label: "No, la plataforma todavía está en construcción" },
        ],
      },
      {
        name: "queSeVende",
        label: "¿Qué se vende u ofrece actualmente?",
        type: "textarea",
        required: true,
        showIf: (data: Record<string, any>) => data.existeAlgoParaVender === "si",
      },
      {
        name: "aQuienSeVende",
        label: "¿A quién se le vende hoy? (propietarios, huéspedes, o ambos)",
        type: "textarea",
        required: true,
        showIf: (data: Record<string, any>) => data.existeAlgoParaVender === "si",
      },
      {
        name: "precioComision",
        label: "¿A qué precio / con qué comisión?",
        type: "text",
        required: true,
        showIf: (data: Record<string, any>) => data.existeAlgoParaVender === "si",
      },
      {
        name: "facturacionMensual",
        label: "¿Cuánto se factura al mes hoy? (aproximado)",
        type: "text",
        required: true,
        showIf: (data: Record<string, any>) => data.existeAlgoParaVender === "si",
      },
      {
        name: "origenClientesHoy",
        label: "¿De dónde llegan hoy los propietarios y los huéspedes?",
        type: "textarea",
        required: true,
        showIf: (data: Record<string, any>) => data.existeAlgoParaVender === "si",
      },
      {
        name: "objecionMasFrecuente",
        label: "¿Qué objeción se escucha más antes de que un propietario liste su propiedad, o antes de que un huésped reserve?",
        type: "textarea",
        required: true,
        showIf: (data: Record<string, any>) => data.existeAlgoParaVender === "si",
      },
      {
        name: "queNoFunciona",
        label: "¿Qué no está funcionando? (honestidad total)",
        type: "textarea",
        required: true,
        showIf: (data: Record<string, any>) => data.existeAlgoParaVender === "si",
      },
      {
        name: "queSabeHacerRocio",
        label: "¿Qué sabés hacer vos (o tu equipo) en este rubro que a otra persona le costaría?",
        type: "textarea",
        required: true,
        showIf: (data: Record<string, any>) => data.existeAlgoParaVender === "no",
      },
      {
        name: "quePreguntanHoy",
        label: "¿Qué te preguntan hoy los propietarios o conocidos de la zona cuando necesitan ayuda para alquilar su propiedad?",
        type: "textarea",
        required: true,
        showIf: (data: Record<string, any>) => data.existeAlgoParaVender === "no",
      },
      {
        name: "aQuienAyudoInformalmente",
        label: "¿A quién ayudaste con esto, aunque haya sido informalmente o gratis?",
        type: "textarea",
        required: true,
        showIf: (data: Record<string, any>) => data.existeAlgoParaVender === "no",
      },
      {
        name: "queIntentoAntes",
        label: "¿Qué intentaste antes (vos o los propietarios de la zona) que no funcionó, y por qué?",
        type: "textarea",
        required: true,
        showIf: (data: Record<string, any>) => data.existeAlgoParaVender === "no",
      },
      {
        name: "tiempoDisponibleSemana",
        label: "¿Cuánto tiempo real por semana podés dedicarle al lanzamiento?",
        type: "text",
        required: true,
        showIf: (data: Record<string, any>) => data.existeAlgoParaVender === "no",
      },
    ],
  },
  {
    id: "punto-cero",
    title: "Punto Cero del Proyecto",
    description: "Cómo se define tu negocio en pocas palabras",
    fields: [
      {
        name: "categoriaNegocio",
        label: "Categoría de tu negocio (elegí hasta 2: Turismo, Real Estate/Propiedades, Tecnología, Economía regional, Emprendimiento)",
        type: "text",
        required: true,
      },
      {
        name: "monedaEntrada",
        label: "¿Cuál es tu 'moneda de entrada' a este negocio? Lo que te da derecho a hablar de esto",
        type: "select",
        required: true,
        options: [
          { value: "experiencia", label: "Experiencia en la zona" },
          { value: "investigacion", label: "Investigación de mercado" },
          { value: "produccion", label: "Producción / trabajo ya hecho" },
          { value: "divulgacion", label: "Divulgación / comunicación" },
          { value: "perspectiva-propia", label: "Perspectiva propia" },
          { value: "combinacion", label: "Una combinación de varias" },
        ],
      },
      {
        name: "rubro",
        label: "¿Cómo definirías el rubro de tu negocio?",
        type: "text",
        required: true,
      },
      {
        name: "nicho",
        label: "¿A quién le hablás exactamente, y en qué momento de su vida o necesidad? (podés separar propietarios y huéspedes si es distinto)",
        type: "textarea",
        required: true,
      },
    ],
  },
  {
    id: "paradigma",
    title: "Tu Paradigma Único",
    description: "Lo que hace que te elijan a vos y no a Airbnb, Booking o el vecino que alquila por su cuenta",
    fields: [
      {
        name: "consensoARomper",
        label: "¿Qué hace todo el mundo hoy en este rubro, que tu proyecto viene a romper?",
        type: "textarea",
        required: true,
      },
      {
        name: "tuPostura",
        label: "Completá: 'El problema no es ___, es ___' (tu forma de ver el problema real)",
        type: "textarea",
        required: true,
      },
      {
        name: "nombreMarca",
        label: "¿Cómo se llama, o te gustaría que se llame, tu marca/marketplace? (2 o 3 palabras)",
        type: "text",
        required: true,
      },
      {
        name: "queSignificaEnConcreto",
        label: "¿Qué significa eso en concreto? Dame 3 características distintivas",
        type: "textarea",
        required: true,
      },
    ],
  },
  {
    id: "historia",
    title: "Tu Historia ⭐",
    description: "Esto se convierte en el contenido de autoridad más importante del lanzamiento. Contame escenas concretas, no cualidades.",
    fields: [
      {
        name: "cuandoEmpezo",
        label: "¿Cuándo empezó? (una fecha o un momento concreto)",
        type: "text",
        required: true,
      },
      {
        name: "elFondo",
        label: "El fondo: ¿cuál era la situación real antes de empezar?",
        type: "textarea",
        required: true,
      },
      {
        name: "elGiro",
        label: "El giro: ¿qué hiciste distinto? (una acción específica y repetible)",
        type: "textarea",
        required: true,
      },
      {
        name: "laPrueba",
        label: "La prueba: resultado concreto, con número si es posible",
        type: "textarea",
        required: true,
      },
      {
        name: "objecionQueDesarma",
        label: "¿Qué objeción le queda sin argumento a alguien después de ver ese resultado?",
        type: "textarea",
        required: true,
      },
      {
        name: "loQueTodaviaCuesta",
        label: "Con honestidad, ¿qué es lo que todavía te cuesta de este proyecto?",
        type: "textarea",
        required: true,
      },
      {
        name: "fraseParaElQueDuda",
        label: "¿Qué frase le dirías a un propietario o huésped que hoy duda?",
        type: "textarea",
        required: true,
      },
    ],
  },
  {
    id: "pruebas",
    title: "Testimonios y Pruebas",
    description: "Si todavía no hay propiedades ni reservas reales, dejalo en blanco y volvé apenas haya el primer caso",
    fields: [
      {
        name: "primerAntesDespues",
        label: "Contame tu primer antes/después, aunque no sea masivo: una propiedad que pasó de vacía a reservada, un propietario que confió antes de que la plataforma esté lista, una captura de WhatsApp con un agradecimiento, etc.",
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "presencia-digital",
    title: "Presencia Digital",
    description: "Si todavía no tenés nada de esto, dejalo en blanco",
    fields: [
      {
        name: "redesExistentes",
        label: "¿Tenés redes sociales de la marca? Pasame usuario y seguidores de Instagram, Facebook y/o TikTok si ya existen",
        type: "textarea",
        required: false,
      },
      {
        name: "bioActual",
        label: "¿Qué dice tu bio hoy, literal?",
        type: "text",
        required: false,
      },
      {
        name: "fotoPerfilCumple",
        label: "Tu foto de perfil actual, ¿mira a cámara, tiene buena luz y fondo limpio?",
        type: "select",
        required: false,
        options: [
          { value: "si", label: "Sí, cumple" },
          { value: "no", label: "No, hay que mejorarla" },
          { value: "no-tengo", label: "Todavía no tengo foto de perfil de marca" },
        ],
      },
    ],
  },
  {
    id: "objetivo-medible",
    title: "Objetivo del Proyecto",
    description: "Lanzar la plataforma funcionando en tu zona, con presencia de marca instalada y las primeras propiedades y reservas reales",
    fields: [
      {
        name: "comoSeVaASaber",
        label: "¿Cómo vas a saber que lo lograste? Dame el número concreto (ej: cantidad de propiedades cargadas, reservas confirmadas en el primer mes, etc.)",
        type: "textarea",
        required: true,
      },
    ],
  },
  {
    id: "diagnostico-negocio",
    title: "Diagnóstico del Negocio",
    description: "Un vistazo honesto a dónde estás parada hoy",
    fields: [
      {
        name: "negocioEnUnaFrase",
        label: "Resumí tu negocio en una frase: a quién ayudás, con qué, y sin qué dolor",
        type: "textarea",
        required: true,
      },
      {
        name: "diferenciacionCorta",
        label: "Tu diferenciación dicha corta (una línea)",
        type: "text",
        required: true,
      },
      {
        name: "cuelloDeBotella",
        label: "Hoy, ¿cuál es tu cuello de botella principal?",
        type: "select",
        required: true,
        options: [
          { value: "visibilidad", label: "Visibilidad (nadie te conoce todavía)" },
          { value: "oferta", label: "Oferta (falta plataforma o propiedades cargadas)" },
          { value: "conversion", label: "Conversión (hay tráfico pero no reservas)" },
          { value: "entrega", label: "Entrega (hay reservas pero falla la operación o el soporte)" },
        ],
      },
      {
        name: "queNoVaAHacer",
        label: "¿Qué tres cosas tu proyecto NO va a hacer, aunque funcionen, porque contradicen tu forma de ver el negocio?",
        type: "textarea",
        required: true,
      },
    ],
  },
  {
    id: "competencia",
    title: "Competencia y Mercado",
    fields: [
      {
        name: "competidoresConcretos",
        label: "Nombrá competidores concretos: inmobiliarias, páginas o perfiles de Instagram que ya operan en tu zona",
        type: "textarea",
        required: true,
      },
      {
        name: "queHacenEllos",
        label: "¿Qué hacen ellos que vos todavía no hacés?",
        type: "textarea",
        required: true,
      },
      {
        name: "quePodesHacerVos",
        label: "¿Qué podés hacer vos que ellos no hacen?",
        type: "textarea",
        required: true,
      },
    ],
  },
  {
    id: "oportunidades",
    title: "Oportunidades",
    fields: [
      {
        name: "oportunidadesIdentificadas",
        label: "¿Qué oportunidades identificás para este proyecto? (hasta 3)",
        type: "textarea",
        required: true,
      },
    ],
  },
  {
    id: "avatar-propietario",
    title: "Avatar: El Propietario/Anfitrión",
    description: "El perfil de cliente ideal del lado del propietario",
    fields: [
      {
        name: "propietarioEscenaDelDia",
        label: "Describí a tu propietario ideal: nombre, edad, y una escena concreta de su día donde aparece el problema (hora, lugar, qué está pensando)",
        type: "textarea",
        required: true,
      },
      {
        name: "propietarioDolores",
        label: "Sus tres dolores principales, con sus propias palabras",
        type: "textarea",
        required: true,
      },
      {
        name: "propietarioIntentoAntes",
        label: "¿Qué ya intentó (publicarla él mismo, una sola inmobiliaria, etc.) y no le funcionó?",
        type: "textarea",
        required: true,
      },
      {
        name: "propietarioObjeciones",
        label: "Sus tres objeciones para no publicar en tu plataforma, y qué las desarma",
        type: "textarea",
        required: true,
      },
      {
        name: "propietarioFraseQueLoConvence",
        label: "¿Qué frase tuya lo haría pensar 'esta plataforma sí entendió mi problema'?",
        type: "textarea",
        required: true,
      },
    ],
  },
  {
    id: "avatar-huesped",
    title: "Avatar: El Huésped/Turista",
    description: "El perfil de cliente ideal del lado del huésped",
    fields: [
      {
        name: "huespedEscenaDelDia",
        label: "Describí a tu huésped ideal: nombre, edad, y una escena concreta de su día donde aparece el problema (hora, lugar, qué está pensando)",
        type: "textarea",
        required: true,
      },
      {
        name: "huespedDolores",
        label: "Sus tres dolores principales, con sus propias palabras",
        type: "textarea",
        required: true,
      },
      {
        name: "huespedIntentoAntes",
        label: "¿Qué ya intentó (reservar por Facebook, pagar sin garantías, etc.) y no le funcionó?",
        type: "textarea",
        required: true,
      },
      {
        name: "huespedObjeciones",
        label: "Sus tres objeciones para no reservar, y qué las desarma",
        type: "textarea",
        required: true,
      },
      {
        name: "huespedFraseQueLoConvence",
        label: "¿Qué frase tuya lo haría pensar 'esta plataforma sí entendió mi problema'?",
        type: "textarea",
        required: true,
      },
    ],
  },
  {
    id: "lenguaje",
    title: "Cómo Hablan Tus Clientes",
    fields: [
      {
        name: "frasesPropietarios",
        label: "Frases que usan los propietarios cuando hablan de esto",
        type: "textarea",
        required: true,
      },
      {
        name: "frasesHuespedes",
        label: "Frases que usan los huéspedes cuando hablan de esto",
        type: "textarea",
        required: true,
      },
      {
        name: "contenidoQueConsumen",
        label: "¿Qué contenido consumen? (cuentas, grupos de Facebook, páginas de turismo de tu zona)",
        type: "textarea",
        required: true,
      },
    ],
  },
  {
    id: "oferta-propietario",
    title: "Tu Oferta al Propietario",
    fields: [
      {
        name: "promesaPropietario",
        label: "¿Cuál es la promesa concreta que le hacés a un propietario?",
        type: "textarea",
        required: true,
      },
      {
        name: "incluyeOfertaPropietario",
        label: "Además de publicar la propiedad y gestionar reservas, ¿qué más incluye tu oferta? (fotografía profesional, check-in/check-out, cobro y liquidación, soporte, etc.)",
        type: "textarea",
        required: true,
      },
      {
        name: "porQueIncomparablePropietario",
        label: "¿Por qué es difícil de copiar? ¿Qué tendría que hacer un competidor para igualarlo?",
        type: "textarea",
        required: true,
      },
      {
        name: "modeloComisionPropietario",
        label: "Modelo de comisión o precio para el propietario (% por reserva, membresía fija, o combinación)",
        type: "text",
        required: true,
      },
    ],
  },
  {
    id: "oferta-huesped",
    title: "Tu Oferta al Huésped",
    fields: [
      {
        name: "promesaHuesped",
        label: "¿Cuál es la promesa concreta que le hacés a un huésped?",
        type: "textarea",
        required: true,
      },
      {
        name: "incluyeOfertaHuesped",
        label: "¿Qué incluye tu oferta al huésped?",
        type: "textarea",
        required: true,
      },
      {
        name: "precioCondicionesHuesped",
        label: "Precio o condiciones de pago para el huésped",
        type: "textarea",
        required: true,
      },
    ],
  },
];
